title: Perimeter Strategies
description: Boutique research and regulatory strategy.

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "#1E293B" 

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
